/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWizardRouteImport } from './routes/app.wizard'
import { Route as AppScenariosRouteImport } from './routes/app.scenarios'
import { Route as AppReceiptRouteImport } from './routes/app.receipt'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppCompareRouteImport } from './routes/app.compare'
import { Route as AppCalculatorRouteImport } from './routes/app.calculator'
import { Route as AppBudgetRouteImport } from './routes/app.budget'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWizardRoute = AppWizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => AppRoute,
} as any)
const AppScenariosRoute = AppScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiptRoute = AppReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppCompareRoute = AppCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculatorRoute = AppCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetRoute = AppBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/budget': typeof AppBudgetRoute
  '/app/calculator': typeof AppCalculatorRoute
  '/app/compare': typeof AppCompareRoute
  '/app/history': typeof AppHistoryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/receipt': typeof AppReceiptRoute
  '/app/scenarios': typeof AppScenariosRoute
  '/app/wizard': typeof AppWizardRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/budget': typeof AppBudgetRoute
  '/app/calculator': typeof AppCalculatorRoute
  '/app/compare': typeof AppCompareRoute
  '/app/history': typeof AppHistoryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/receipt': typeof AppReceiptRoute
  '/app/scenarios': typeof AppScenariosRoute
  '/app/wizard': typeof AppWizardRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/budget': typeof AppBudgetRoute
  '/app/calculator': typeof AppCalculatorRoute
  '/app/compare': typeof AppCompareRoute
  '/app/history': typeof AppHistoryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/receipt': typeof AppReceiptRoute
  '/app/scenarios': typeof AppScenariosRoute
  '/app/wizard': typeof AppWizardRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/budget'
    | '/app/calculator'
    | '/app/compare'
    | '/app/history'
    | '/app/profile'
    | '/app/receipt'
    | '/app/scenarios'
    | '/app/wizard'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/budget'
    | '/app/calculator'
    | '/app/compare'
    | '/app/history'
    | '/app/profile'
    | '/app/receipt'
    | '/app/scenarios'
    | '/app/wizard'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/budget'
    | '/app/calculator'
    | '/app/compare'
    | '/app/history'
    | '/app/profile'
    | '/app/receipt'
    | '/app/scenarios'
    | '/app/wizard'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wizard': {
      id: '/app/wizard'
      path: '/wizard'
      fullPath: '/app/wizard'
      preLoaderRoute: typeof AppWizardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scenarios': {
      id: '/app/scenarios'
      path: '/scenarios'
      fullPath: '/app/scenarios'
      preLoaderRoute: typeof AppScenariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/receipt': {
      id: '/app/receipt'
      path: '/receipt'
      fullPath: '/app/receipt'
      preLoaderRoute: typeof AppReceiptRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compare': {
      id: '/app/compare'
      path: '/compare'
      fullPath: '/app/compare'
      preLoaderRoute: typeof AppCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calculator': {
      id: '/app/calculator'
      path: '/calculator'
      fullPath: '/app/calculator'
      preLoaderRoute: typeof AppCalculatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/budget': {
      id: '/app/budget'
      path: '/budget'
      fullPath: '/app/budget'
      preLoaderRoute: typeof AppBudgetRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBudgetRoute: typeof AppBudgetRoute
  AppCalculatorRoute: typeof AppCalculatorRoute
  AppCompareRoute: typeof AppCompareRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReceiptRoute: typeof AppReceiptRoute
  AppScenariosRoute: typeof AppScenariosRoute
  AppWizardRoute: typeof AppWizardRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBudgetRoute: AppBudgetRoute,
  AppCalculatorRoute: AppCalculatorRoute,
  AppCompareRoute: AppCompareRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppProfileRoute: AppProfileRoute,
  AppReceiptRoute: AppReceiptRoute,
  AppScenariosRoute: AppScenariosRoute,
  AppWizardRoute: AppWizardRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
